# kubectl port-forward service/observatorium-xyz-observatorium-api 8090:8090 8050:8080
# docker run --rm -it --net=host -v $PWD:/tmp/conf ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector:0.61.0 --config /tmp/conf/addon_otelcol.yaml
# access Jaeger UI: http://localhost:8050/api/traces/v1/test-oidc/search
# it requires 192.168.49.2 hydra.hydra.svc.cluster.local in /etc/hosts - The IP address is minikube ip
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.66.0
  config: |
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"

    receivers:
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          thrift_binary:
          thrift_compact:
          thrift_http:
          grpc:

    processors:

    exporters:
      otlp:
        endpoint: observatorium-xyz-observatorium-api.ploffay.svc.cluster.local:8090
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Tenant: "test-oidc"

    service:
      telemetry:
        logs:
          level: "DEBUG"
          development: true
          encoding: "json"
      extensions: [bearertokenauth]
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          exporters: [otlp]
---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: collector-observatorium
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: fixme # TODO
#subjects:
#  - kind: ServiceAccount
#    name: simplest-collector
#    namespace: ploffay
